# Generated by Django 5.0.4 on 2024-04-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
